config/routes.rb
Searchflickr::Application.routes.draw do
  resources :images, only: [:new, :index]

  root 'images#new'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
  end

  def index
    @query = params[:search]
    if @query.empty?
      @image_array = flickr.photos.getRecent.to_a
    else
      @image_array = flickr.photos.search(tags: @query, sort: 'relevance').to_a
    end
    @results = Kaminari.paginate_array(@image_array).page(params[:page]).per(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/index.html.haml
.container-fluid
  = render partial: 'shared/header'
  .row-fluid.results-header
    .span12
      %h3
        - if @query.empty?
          Showing the most recent images
        - else
          Search results for
          %span
            "#{@query}"
  = render partial: 'shared/pagination'
  .row-fluid.results-grid
    - if @results.count > 0
      - @results.each_slice(4) do |group|
        .row-fluid.image-row
          - group.each do |photo|
            .span3.image-tile
              %a{class: 'image-link', href: '#', 'data-mfp-src' => "#{FlickRaw.url_z(photo)}"}
                = image_tag(FlickRaw.url_m(photo), alt: '')
    - else
      .span12
        %p No images were found.
  = render partial: 'shared/pagination'

app/views/images/new.html.haml
- content_for :javascript do
  :javascript
    $.vegas('slideshow', {
    backgrounds:[
      { src:'#{asset_path 'background-1.jpg'}', fade:2000 },
      { src:'#{asset_path 'background-2.jpg'}', fade:2000 },
      { src:'#{asset_path 'background-3.jpg'}', fade:2000 }
    ]});

.container-fluid
  .row-fluid
    .span12
      %h1.logo-front.text-center
        = link_to 'Search Flickr.', root_path
    .span12
      = form_tag images_path, method: 'get', class: 'navbar-form new-search text-center' do
        %span
          = text_field_tag :search, nil, placeholder: 'enter a keyword'
        %span
          = submit_tag 'Search', name: nil, class: 'btn btn-success'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Search Flickr
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Oxygen:400,300,700'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Ledger'
    = csrf_meta_tags
  %body
    .content
      - if flash[:notice]
        .container-fluid.flash
          .row-fluid
            .span12
              .alert.alert-success= flash[:notice]
      - if flash[:error]
        .container-fluid.flash
          .row-fluid
            .span1
              .alert.alert-success= flash[:error]
      = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = yield :javascript

app/views/shared/_header.html.haml
.row-fluid.header
  .span4
    %h1.logo
      = link_to 'Search Flickr.', root_path
  .span8
    = form_tag images_path, method: 'get', class: 'navbar-form header-search' do
      %span
        - if @query.empty?
          = text_field_tag :search, nil, placeholder: 'enter a keyword'
        - else
          = text_field_tag :search, nil, placeholder: params[:search]
      %span
        = submit_tag 'Search', name: nil, class: 'btn btn-success'

app/views/shared/_pagination.html.haml
.row-fluid.paginate-bar
  .span12
    %p
      = paginate @results